import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  paper: {
    marginTop: theme.spacing(6),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: theme.spacing(4),
    background: 'linear-gradient(135deg, rgba(255,255,255,0.95) 0%, rgba(255,255,255,0.9) 100%)',
    backdropFilter: 'blur(10px)',
    borderRadius: 24,
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.12)',
    border: '1px solid rgba(255, 255, 255, 0.5)',
    maxWidth: 440,
    width: '100%',
  },
  root: {
    '& .MuiTextField-root': {
      margin: theme.spacing(1.5, 0),
    },
    '& .MuiOutlinedInput-root': {
      borderRadius: 12,
      '&:hover .MuiOutlinedInput-notchedOutline': {
        borderColor: theme.palette.primary.main,
      },
    },
  },
  avatar: {
    margin: theme.spacing(2),
    width: 64,
    height: 64,
    background: 'linear-gradient(135deg, #00D4AA 0%, #FF6B6B 100%)',
    fontSize: '2rem',
    fontWeight: 700,
  },
  form: {
    width: '100%',
    marginTop: theme.spacing(2),
  },
  submit: {
    margin: theme.spacing(3, 0, 2),
    background: 'linear-gradient(135deg, #00D4AA 0%, #00A888 100%)',
    color: '#fff',
    fontWeight: 600,
    padding: '12px 24px',
    borderRadius: 12,
    boxShadow: '0 4px 14px 0 rgba(0, 212, 170, 0.3)',
    '&:hover': {
      background: 'linear-gradient(135deg, #00A888 0%, #00D4AA 100%)',
      boxShadow: '0 6px 20px 0 rgba(0, 212, 170, 0.4)',
    },
  },
  googleButton: {
    marginBottom: theme.spacing(2),
    marginTop: theme.spacing(1),
    backgroundColor: '#fff !important',
    color: '#2D3748 !important',
    borderColor: '#E2E8F0 !important',
    textTransform: 'none',
    fontSize: '15px',
    fontWeight: 600,
    padding: '12px 24px',
    borderRadius: 12,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08) !important',
    border: '1.5px solid #E2E8F0 !important',
    '&:hover': {
      backgroundColor: '#F7FAFC !important',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.12) !important',
      borderColor: '#CBD5E0 !important',
    },
    '& .MuiButton-startIcon': {
      marginRight: theme.spacing(1.5),
    },
  },
  footerLinks: {
    width: '100%',
    marginTop: theme.spacing(3),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: theme.spacing(1),
  },
  linkText: {
    background: 'linear-gradient(135deg, #00D4AA 0%, #00A888 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    textDecoration: 'none',
    marginBottom: theme.spacing(0.5),
    transition: 'all 0.2s',
    '&:hover': {
      textDecoration: 'underline',
      textDecorationColor: theme.palette.primary.main,
    },
  },
  signUpLink: {
    color: theme.palette.text.secondary,
    fontSize: '14px',
    fontWeight: 400,
    textAlign: 'center',
  },
  linkSpan: {
    background: 'linear-gradient(135deg, #00D4AA 0%, #00A888 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    fontWeight: 600,
    textDecoration: 'none',
    cursor: 'pointer',
    '&:hover': {
      textDecoration: 'underline',
      textDecorationColor: theme.palette.primary.main,
    },
  },
}));
