import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  media: {
    height: 0,
    paddingTop: '56.25%',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    backgroundBlendMode: 'overlay',
    position: 'relative',
    '&::after': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.4) 100%)',
    },
  },
  border: {
    border: 'none',
  },
  fullHeightCard: {
    height: '100%',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    borderRadius: 20,
    height: '100%',
    position: 'relative',
    background: '#fff',
    overflow: 'hidden',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    '&:hover': {
      transform: 'translateY(-8px)',
      boxShadow: '0 12px 40px rgba(0, 0, 0, 0.15)',
    },
  },
  overlay: {
    position: 'absolute',
    top: '16px',
    left: '16px',
    color: 'white',
    zIndex: 2,
    background: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(8px)',
    padding: '8px 16px',
    borderRadius: 20,
    fontWeight: 600,
    fontSize: '0.875rem',
  },
  overlay2: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    color: 'white',
    zIndex: 2,
    background: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(8px)',
    borderRadius: '50%',
    padding: '8px',
  },
  grid: {
    display: 'flex',
  },
  details: {
    display: 'flex',
    justifyContent: 'space-between',
    margin: '16px',
    flexWrap: 'wrap',
    gap: '8px',
  },
  title: {
    padding: '0 20px',
    fontWeight: 600,
    fontSize: '1.25rem',
    color: theme.palette.text.primary,
    lineHeight: 1.4,
  },
  cardActions: {
    padding: '12px 20px 16px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTop: '1px solid rgba(0, 0, 0, 0.06)',
  },
  cardAction: {
    display: 'block',
    textAlign: 'initial',
    width: '100%',
  },
  tag: {
    background: 'linear-gradient(135deg, #00D4AA 0%, #00A888 100%)',
    color: 'white',
    padding: '4px 12px',
    borderRadius: 12,
    fontSize: '0.75rem',
    fontWeight: 600,
    display: 'inline-block',
    marginRight: '6px',
    marginBottom: '4px',
  },
}));
